# Generated by Django 5.1.4 on 2024-12-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='process',
            field=models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_FEEDBACK', 'Awaiting Feedback'), ('DONE', 'Done')], default='TO_DO', max_length=20),
        ),
    ]
