# Generated by Django 5.1.4 on 2025-01-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0002_task_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='color',
            field=models.IntegerField(default=0),
        ),
    ]
