# Generated by Django 5.1.4 on 2025-01-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0003_contact_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
