# Generated by Django 5.1.4 on 2025-01-23 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0004_rename_name_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtasks',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='join_app.subtasks'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.date(2099, 12, 31)),
        ),
    ]
