# Generated by Django 5.1.4 on 2025-01-23 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0005_remove_subtasks_task_task_subtasks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='assignees',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='process',
            new_name='status',
        ),
    ]
