# Generated by Django 5.1.4 on 2025-01-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0007_remove_task_subtasks_remove_task_date_task_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='date',
        ),
    ]
