# Generated by Django 5.1.4 on 2025-01-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0009_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('awaiting_feedback', 'Awaiting Feedback'), ('done', 'Done')], default='to_do', max_length=20),
        ),
    ]
