# Generated by Django 5.1.4 on 2025-01-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0010_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('awaiting_feedback', 'Awaiting Feedback'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
