# Generated by Django 5.1.4 on 2025-01-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0012_alter_task_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subtask',
            new_name='Subtasks',
        ),
    ]
