# Generated by Django 5.1.4 on 2025-01-25 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0015_remove_task_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasks',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='join_app.task'),
        ),
    ]
