# Generated by Django 5.1.4 on 2025-01-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0017_alter_subtasks_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('progress', 'In Progress'), ('awaiting', 'Awaiting Feedback'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
