# Generated by Django 5.1.4 on 2025-01-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0019_category_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_color',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
